version: '3.2'
services:
    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        image: langflow_back:v0.1
        container_name: langflow_application_back
        volumes:
          - ./backend:/backend
        ports:
          - 6767:6767
        network_mode: host
        command: python app.py

    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        image: langflow_front:v0.1
        container_name: langflow_application_front
        volumes:
          - ./frontend:/frontend
        ports:
          - 3000:3000
        network_mode: host
        command: npm start
