version: '3.2'
services:
    backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        image: langflow_back:v0.1
        container_name: langflow_application_back
        volumes:
          - ./backend:/backend
        ports:
          - 6767:6767
        network_mode: host
        command: python app.py

    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        image: langflow_front:v0.1
        container_name: langflow_application_front
        volumes:
          - ./frontend:/frontend
        ports:
          - 3000:3000
        network_mode: host
        command: npm start

    postgres:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
      volumes:
         - ./backend/data/postgresql:/var/lib/postgres/data
      ports:
        - "5432:5432"
      networks:
        - postgres-net
      restart: unless-stopped

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: langflow@russia.win
        PGADMIN_DEFAULT_PASSWORD: 123456
      volumes:
         - ./backend/data/pgadmin:/var/lib/pgadmin/data
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      depends_on:
        - postgres
      networks:
        - postgres-net
      restart: unless-stopped

networks:
  postgres-net:
    driver: bridge

volumes:
    postgres:
    pgadmin:
